common: &common
  adapter: postgresql
  host: localhost
  port: 5432 
  pool: 5
  encoding: UTF8

development:
  <<: *common
  database: notitest_dev 
  username: dev   
  password: secret

test:
  <<: *common
  database: notitest_test
  username: test   
  password: secret

production:
  <<: *common
  database: notitest_prod 
  username: notitest   
  password: supersecret                 